---
# optional name of project (default name is the directory)
name: vtide
# the total number of terminals to start up
count: 10
# inheriting content from parent yaml file (defaults in this case)
parent: ./.vtide-parent.yml
# configure your editor
env:
  test: true
editor:
  # the command to run
  command:
    # this will run vim -O plus what ever files are found but the files config
    - vim
      -O
  helper: |
    sub {
        $_[1] eq 'json' ? ('*.json') : ()
    }
  # files store the named file groups
  files:
    all:
      - '**/*'
    all-tests:
      - t/**/*.t
    bin:
      - bin/*
    lib:
      - lib/**/*.pm
      - lib/**/*.pom
    base:
      - lib/App/VTide.pm
      - lib/App/VTide/Config.pm
      - lib/App/VTide/Hooks.pm
      - lib/App/VTide/Sessions.pm
    cmds:
      - lib/App/VTide/Command.pm
      - lib/App/VTide/Command/Init.pm
      - lib/App/VTide/Command/Start.pm
    helpers:
      - lib/App/VTide/Command/Conf.pm
      - lib/App/VTide/Command/Refresh.pm
      - lib/App/VTide/Command/Recent.pm
      - lib/App/VTide/Command/List.pm
    rest:
      - lib/App/VTide/Command/Split.pm
      - lib/App/VTide/Command/Grep.pm
      - lib/App/VTide/Command/Help.pm
    meta:
      - lib/App/VTide/Command/Who.pm
      - lib/App/VTide/Command/History.pm
      - lib/App/VTide/Command/Help.pm
      - lib/App/VTide/Command/NewWindow.pm
    run:
      - lib/App/VTide/Command/Run.pm
      - lib/App/VTide/Command/Edit.pm
      - lib/App/VTide/Command/Save.pm
    base-tests:
      - t/boilerplate.t
      - t/critic.t
      - t/kwalitee.t
      - t/manifest.t
      - t/perlcriticrc
      - t/pod-coverage.t
      - t/pod.t
      - t/spelling.t
    test:
      - t/00-load.t
      - t/vtide.t
      - t/vtide-config.t
      - t/glob.t
    cmd-tests:
      - t/vtide-cmd*.t
    all-tests:
      - t/*.t
# Start up options
start:
  # Running ctags every time vtide is started
  # This specifies the files to run
  #ctags: -R
  # list of ctag-exclude groups or directories
  ctags-exclude:
    - perl
    - tmp/
  # Specify groups of directories to exclude
  # This can be used to specify global lists of excludes in ~/.vtide.yml
  ctags-excludes:
    perl:
      - blib
      - _build
      - Build
# configure the individual terminals
terminals:
  1:
    # splits once horizontally then once vertically for a large vertical
    # left hand terminal and two smaller right hand terminals, the focus
    # being sent to the 1st pane (pane 0)
    split: Hvv0
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    # watch is a list of files (or file groups) to watch for changes and
    # re-run the command. This watch waits for changes in files in the
    # lib bin and tests directories and then runs tests
    watch:
      - lib
      - bin
      - all-tests
  1b:
    restart: 1
    wait: 0
    command: git status
    watch:
      - all
  1c:
    env:
      IVAN: true
  2:
    edit:
      - base
  3:
    edit:
      - cmds
  4:
    edit:
      - run
  5:
    edit:
      - helpers
  6:
    edit:
      - rest
  7:
    edit:
      - meta
  8:
    edit:
      - test
  9:
    edit:
      - cmd-tests
