---
# optional name of project (default name is the directory)
name: vtide
# the total number of terminals to start up
count: 10
# default configs for terminals
default:
  env:
    PERL5LIB: lib:$PERL5LIB
  # when the command finishes restart the command (useful for running
  # dev servers which may die or you may want to kill and restart)
  restart: 0
  # run the command at first start or wait for the user to press enter
  wait: 1
# configure your editor
editor:
  # the command to run
  command:
    # this will run vim -O plus what ever files are found but the files config
    - vim
      -O
  helper: |
    sub {
        $_[1] eq 'json' ? ('*.json') : ()
    }
  # files store the named file groups
  files:
    all:
      - '**/*'
    all-tests:
      - t/**/*.t
    base:
      - lib/App/VTide.pm
      - lib/App/VTide/Config.pm
      - lib/App/VTide/Hooks.pm
    base-tests:
      - t/boilerplate.t
      - t/critic.t
      - t/kwalitee.t
      - t/manifest.t
      - t/perlcriticrc
      - t/pod-coverage.t
      - t/pod.t
      - t/spelling.t
    bin:
      - bin/*
    cmds:
      - lib/App/VTide/Command.pm
      - lib/App/VTide/Command/Init.pm
      - lib/App/VTide/Command/Start.pm
    helpers:
      - lib/App/VTide/Command/Conf.pm
      - lib/App/VTide/Command/Help.pm
      - lib/App/VTide/Command/Refresh.pm
    rest:
      - lib/App/VTide/Command/Split.pm
      - lib/App/VTide/Command/Recent.pm
      - lib/App/VTide/Command/Grep.pm
    lib:
      - lib/**/*.pm
      - lib/**/*.pom
    run:
      - lib/App/VTide/Command/Run.pm
      - lib/App/VTide/Command/Edit.pm
      - lib/App/VTide/Command/Save.pm
    test:
      - t/00-load.t
      - t/vtide.t
      - t/vtide-config.t
      - t/glob.t
    cmd-tests:
      - t/vtide-cmd*.t
    all-tests:
      - t/*.t
# configure the individual terminals
terminals:
  1:
    # splits once horizontally then once vertically for a large vertical
    # left hand terminal and two smaller right hand terminals, the focus
    # being sent to the 1st pane (pane 0)
    split: Hv0
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    # watch is a list of files (or file groups) to watch for changes and
    # re-run the command. This watch waits for changes in files in the
    # lib bin and tests directories and then runs tests
    watch:
      - lib
      - bin
      - all-tests
  1b:
    restart: 1
    wait: 0
    command: git status
    watch:
      - all
  2:
    edit:
      - base
  3:
    edit:
      - cmds
  4:
    edit:
      - run
  5:
    edit:
      - helpers
  6:
    edit:
      - rest
  7:
    edit:
      - test
  8:
    edit:
      - cmd-tests
